apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: portfolio-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: dev.jimmy.codes
      http:
        paths:
          - path: /
            backend:
              serviceName: portfolio-svc-dev
              servicePort: 80
