name: Lerna Pull Request CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --prune

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      - name: 'Build: Pull Requests'
        if: github.event_name == 'pull_request'
        run: |
          yarn affected:test
          yarn affected:build

      - name: 'Build: Push'
        if: github.event_name == 'push'
        run: |
          yarn test
          yarn build
