name: Release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test

  lerna-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          fetch-depth: 0
        uses: actions/checkout@v2

      - name: Fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Configure Git
        run: |
          git config --global user.name '@jimmy-guzman'
          git config --global user.email 'jimmy.guzman@outlook.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare repository
        run: |
          git checkout "${GITHUB_REF:11}"
          git pull

      - name: Configure NPM Registry
        uses: actions/setup-node@v1
        with:
          scope: '@jimmy-guzman'
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Yarn install
        run: 'yarn install --frozen-lockfile'

      - name: Publish to NPM
        run: |
          yarn release:npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
